config/routes.rb
Rails.application.routes.draw do
  root to: 'page#home'
  get '/selenium', to: 'page#selenium'
  get '/demo1', to: 'demo1#index'
  get '/demo1/admin', to: 'demo1#admin'
  get '/demo1/admin/posts', to: 'demo1#posts'
  get '/form', to: 'page#form'
  post '/form' => 'page#form'
  get '/users_reg', to: 'page#users_reg'
  # get '/etsdemo', to: 'page#etsdemo'
  # post '/etsdemo' => 'page#etsdemo'

  resources :microposts
  resources :users
  resources :demo1

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts
  default_scope -> { order('created_at DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demo1_controller.rb
class Demo1Controller < ApplicationController
  def index
    @microposts = Micropost.all
    @users=User.all
    # render layout:'layouts/demo'
    # render template: 'layouts/demo1'
  end
  def admin
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @user=User.all
    @microposts = Micropost.all
    render layout: 'demo1_admin'
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    render layout: 'demo1_admin'
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
    render layout: 'demo1_admin'
  end

  # GET /microposts/1/edit
  def edit
    render layout: 'demo1_admin'
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  include ApplicationHelper
  def selenium
    @title="QA Selenium Automatic test"
    render layout: "application2"
  end
  def form
  end
  def home
  end
  def etsdemo
    @report=[]
    if params['commit']=="Go"
      start_ets
      login_ets
    end
    if params['checker']=='1'
      sent_mail_ets
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    render layout: 'demo1_admin'
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @microposts = Micropost.where(user_id: @user.id)
    # @microposts = Micropost.new
    @microposts_new_user=Micropost.new
    @microposts_new_user.user_id=@user.id
    # @microposts_new_user.content="test"
    # @microposts_new_user.save
    render layout: 'demo1_admin'
  end

  # GET /users/new
  def new
    @user = User.new
    render layout: 'demo1_admin'
  end

  # GET /users/1/edit
  def edit
    render layout: 'demo1_admin'
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    @microposts = Micropost.where(user_id: @user.id)
    @microposts.destroy_all()
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_controller_helper.rb
module PageControllerHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/demo1/index.html.erb
<% @microposts.each do |post| %>
<div class="card bg-light mb-3">
  <div class="card-header">
    <%@user=@users.find_by id: post.user_id %>
    <%= @user.name %>
  </div>
  <div class="card-body">
    <p class="card-text">    <%= post.content %></p>
    <p class="card-text" style="font-size: 10px;">      <%= post.created_at %></p>
  </div>
</div>

<% end %>

app/views/demo1/menu.html.erb
<td><%= link_to '<button type="button" class="btn btn-light">User</button>'.html_safe, demo1_path  %></td>
<td><%= link_to '<button type="button" class="btn btn-light">Admin</button>'.html_safe, users_path  %></td>

app/views/demo1/menu_admin.html.erb
<td><%= link_to '<button type="button" class="btn btn-light">Users</button>'.html_safe, users_path  %></td>
<td><%= link_to '<button type="button" class="btn btn-light">Mircoposts</button>'.html_safe, microposts_path  %></td>

app/views/demo1/posts.html.erb
<%=render template: 'microposts/index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=@title%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_default.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/demo1.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Rails demo1</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %></head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<body>
<div class="container">
  <div class="text-right">
    <%=render template: 'demo1/menu' %>
  </div>
  <h1>User</h1>
  <%#=render template: 'demo1/menu_admin' %>
  <%=yield %>
</div>

</body>
</html>

app/views/layouts/demo1_admin.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Rails demo1</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %></head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<body>
<div class="container">
  <div class="text-right">
    <%=render template: 'demo1/menu' %>
  </div>
  <h1>Admin</h1>
  <%=render template: 'demo1/menu_admin' %>
  <%=yield %>
</div>

</body>
</html>

app/views/microposts/_form.html.erb
<h1></h1>
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.collection_select(:user_id, User.all, :id, :name) %>
  </div>

  <div class="input-group mb-3">
    <%= form.text_field :content, class: 'form-control', placeholder: :content%>
    <div class="input-group-append">
      <%= form.submit 'Ок', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to '<button type="button" class="btn btn-secondary btn-sm">Назад</button>'.html_safe, microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>
<%= link_to '<button type="button" class="btn btn-success btn-sm">Добавить</button>'.html_safe, new_micropost_path %>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>id</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.id %></td>
        <td style="width: 100%"><%= micropost.content %></td>

        <%@user=User.find_by id: micropost.user_id %>
        <td><%= @user.name %></td>
        <td><%= link_to '<button type="button" class="btn btn-success btn-sm">Обзор</button>'.html_safe, micropost %></td>
        <td><%= link_to '<button type="button" class="btn btn-primary btn-sm">Править</button>'.html_safe, edit_micropost_path(micropost)%></td>
        <td><%= link_to '<button type="button" class="btn btn-danger btn-sm">Удалить</button>'.html_safe, micropost, method: :delete, data: { confirm: 'Are you sure?' }%></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/microposts/index_table.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>id</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.id %></td>
        <td style="width: 100%"><%= micropost.content %></td>

        <%@user=User.find_by id: micropost.user_id %>
        <td><%= @user.name %></td>
        <td><%= link_to '<button type="button" class="btn btn-success btn-sm">Обзор</button>'.html_safe, micropost %></td>
        <td><%= link_to '<button type="button" class="btn btn-primary btn-sm">Править</button>'.html_safe, edit_micropost_path(micropost)%></td>
        <td><%= link_to '<button type="button" class="btn btn-danger btn-sm">Удалить</button>'.html_safe, micropost, method: :delete, data: { confirm: 'Are you sure?' }%></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to '<button type="button" class="btn btn-secondary btn-sm">Назад</button>'.html_safe, microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to '<button type="button" class="btn btn-primary btn-sm">Править</button>'.html_safe, edit_micropost_path(@micropost) %>
<%= link_to '<button type="button" class="btn btn-secondary btn-sm">Назад</button>'.html_safe, microposts_path %>

app/views/page/etsdemo.html.erb
<h1>ETS Demo</h1>
<h3>с интерфейсом на Ruby on Rails</h3>

<%= form_tag  etsdemo_path do %>
  логин <br>
  <%=text_field_tag(:login, value='etsdemo')  %>
  <br>
  пароль <br>
  <%=password_field_tag(:password, value='2241ets')  %>
  <br>
  <%= check_box_tag(:checker) %>
  <%= label_tag(:checker, "Написать письмо?") %>
  <br>
  Кому <br>
  <%=text_field_tag(:to, value='etsdemo@mail.ru')  %>
  <br>
  Тема <br>
  <%=text_field_tag(:title, value='Mail from Selenium')  %>
  <br>
  Сообщение <br>
  <%=text_field_tag(:msg, value='Hello')  %>
  <br><br>
  <%= submit_tag("Go", class: 'btn btn-success btn-block') %>
<% end %>
<% if params['commit']=="Go"%>
  <h1>result</h1>
  <%#= params%>
  <% @report.each do |element| %>
    <li><%= element %></li>
  <% end %>
<%end %>

app/views/page/form.html.erb
<h1>form</h1>

<%= form_tag  form_path do %>
  x=
  <%=text_field_tag(:x, value=1)  %>
  <br>
  y=
  <%=text_field_tag(:y, value=2)  %>
  <br>
Выберите цвет
<%= radio_button_tag(:radio, 1, checked=true) %>
<%= label_tag(:radio1,"Черный") %>
<%= radio_button_tag(:radio, 2) %>
<%= label_tag(:radio2, "Белый") %>
  <br>
  Машина <%= select_tag(:car, raw('<option value="1">Mercedes</option><option value="2">BMV</option>')) %>
  <br>
  <%= check_box_tag(:checker) %>
  <%= label_tag(:checker, "Checkbox") %>

<%#= select_tag(:city_id, raw('<option value="1">Lisbon</option><option value="2">Madrid</option><option value="3">Berlin</option>')) %>
  <br>
  <%= submit_tag("Go") %>
<% end %>
<h1>result</h1>
<% if params['commit']=="Go"%>
  x=<%=params['x'] %>
  <br>
  y=<%=params['y'] %>
  <br>
  <%="sum=#{params['x'].to_i+params['y'].to_i if params['x']}"%>
<br>
Цвет =
<%="черный" if params['radio']=='1'%>
<%="белый" if params['radio']=='2'%>
  <br>
  Машина =
  <%="Mercedes" if params['car']=='1'%>
  <%="BMV" if params['car']=='2'%>
  <br>
  <%= "Checkbox=uncheck" if params['checker']!='1'%>
  <%= "Checkbox=cheked" if params['checker']=='1'%>
<%end %>

app/views/page/users_reg.html.erb
<h1>hello</h1>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <%= form.text_field :name, class: 'form-control', placeholder: :name%>
    <div class="input-group-append">
      <%= form.submit 'Ок', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to '<button type="button" class="btn btn-secondary btn-sm">Назад</button>'.html_safe, users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<%= link_to '<button type="button" class="btn btn-success btn-sm">Добавить</button>'.html_safe, new_user_path %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td style="width: 100%"><%= user.name %></td>
        <td><%= link_to '<button type="button" class="btn btn-success btn-sm">Обзор</button>'.html_safe, user %></td>
        <td><%= link_to '<button type="button" class="btn btn-primary btn-sm">Править</button>'.html_safe, edit_user_path(user)%></td>
        <td><%= link_to '<button type="button" class="btn btn-danger btn-sm">Удалить</button>'.html_safe, user, method: :delete, data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to '<button type="button" class="btn btn-secondary btn-sm">Назад</button>'.html_safe, users_path %>

app/views/users/show.html.erb
<h1>User</h1>
<p id="notice"><%= notice %></p>
<p>
  <strong>id:</strong>
  <%= @user.id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to '<button type="button" class="btn btn-primary btn-sm">Править</button>'.html_safe, edit_user_path(@user) %>
<%= link_to '<button type="button" class="btn btn-secondary btn-sm">Назад</button>'.html_safe, users_path %>



<p id="notice"><%= notice %></p>

<div id="121">
  <%=form_for @microposts_new_user do |f|%>
    <%=f.text_field :user_id, :style=>'display: none'%>
    <div class="input-group mb-3">
      <%=f.text_field :content, class: 'form-control', placeholder: 'New micropost'%>
      <div class="input-group-append">
        <%= submit_tag 'Ок', class: 'btn btn-success' %>
      </div>
    </div>

<% end %>
</div>
<h1>Microposts</h1>
<%= render template: 'microposts/index_table' %>
Всего постов <%= @microposts.count%>